spring.datasource.url=jdbc:clickhouse://localhost:8123/test_db?compress_algorithm=gzip
spring.datasource.username=default
spring.datasource.password=
spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
spring.jpa.hibernate.ddl-auto=none  # ??? ?????? ??????? ??? ??????
spring.security.enabled=false
jwt.secret=eW91ci1zZWNyZXQta2V5LWhlcmUtZ2VuZXJhdGVkLWJ5LW9wZW5zc2wtcGVyZmVjdC1mb3Itand0

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Super606000A
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myalias


