version: '3'
services:
  # Сервис для Java-приложения
  app:
    build: .
    container_name: java-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - influxdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mysql
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: fN0LMtZOBct_OEjMrYDc2_POBLJcDMPvBle_e7sNx1nwlw4lDDmak0iJ3Ceer204zC9aPSwOM_TPppvLZ9qqCA==
      INFLUXDB_ORG: MultiSens
      INFLUXDB_BUCKET: MultiSens
    networks:
      - app-network

  # Сервис для MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  # Сервис для InfluxDB
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: MultiSens
      DOCKER_INFLUXDB_INIT_BUCKET: MultiSens
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: fN0LMtZOBct_OEjMrYDc2_POBLJcDMPvBle_e7sNx1nwlw4lDDmak0iJ3Ceer204zC9aPSwOM_TPppvLZ9qqCA==
    ports:
      - "8086:8086"
    networks:
      - app-network
    volumes:
      - influxdb-data:/var/lib/influxdb2

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  influxdb-data:
