spring.datasource.url=jdbc:mysql://mysql:3306/mysql
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


influx.url=http://influxdb:8086/api/v2/write
influx.queryUrl=http://influxdb:8086/api/v2/query
influx.authToken=fN0LMtZOBct_OEjMrYDc2_POBLJcDMPvBle_e7sNx1nwlw4lDDmak0iJ3Ceer204zC9aPSwOM_TPppvLZ9qqCA==
influx.org=MultiSens
influx.bucket=MultiSens



jwt.secret=eW91ci1zZWNyZXQta2V5LWhlcmUtZ2VuZXJhdGVkLWJ5LW9wZW5zc2wtcGVyZmVjdC1mb3Itand0
refresh.jwt.secret=eWmK6jiP7hsas9vjgnmZv1eNl30sLJSfDO9RhZvnDT9s9wipjffADGRg6kFvLs1k


#server.port=8443
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=Super606000A
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=myalias


